[project]
name = "cerebrosphere-server"
version = "0.0.1"
description = "A server for the Cerebrosphere project"
readme = "README.md"
requires-python = ">=3.11.6"
dependencies = [
    "flask>=3.1.1",
    "flask-migrate>=4.1.0",
    "flask-sqlalchemy>=3.1.1",
    "rich>=14.0.0",
]
