"""Adds private field

Revision ID: 2065de701b55
Revises: c65688bc8ced
Create Date: 2025-07-05 09:33:07.219228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2065de701b55'
down_revision = 'c65688bc8ced'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_private', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.drop_column('_private')

    # ### end Alembic commands ###
