"""Initial migration

Revision ID: 9daaca4f9716
Revises: 
Create Date: 2025-07-01 22:42:59.221217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9daaca4f9716'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entity_properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_a', sa.Integer(), nullable=False),
    sa.Column('entity_b', sa.Integer(), nullable=False),
    sa.Column('link_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['entity_a'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['entity_b'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('links')
    op.drop_table('entity_properties')
    op.drop_table('entities')
    # ### end Alembic commands ###
